services:

  pg:
    image: postgres:16-alpine
    environment:
      - POSTGRES_DB=myblog
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=12345678
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 30s
      timeout: 30s
      retries: 3
    restart: on-failure
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./sql://docker-entrypoint-initdb.d
    profiles: [ 'dev' ]

  pg-integration-test:
    image: postgres:16-alpine
    environment:
      - POSTGRES_DB=test
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=1234
    ports:
      - "55432:5432"
    profiles: [ 'integration' ]
    tmpfs:
      - /var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    volumes:
      - pgadmin-data:/var/lib/pgadmin

volumes:
  pgdata:
  pgadmin-data:
